--
-- PostgreSQL database dump
--

-- Dumped from database version 15.5
-- Dumped by pg_dump version 15.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: log_folios_changes(); Type: FUNCTION; Schema: public; Owner: panaproperty
--

CREATE FUNCTION public.log_folios_changes() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    INSERT INTO FoliosHistory (
        FOLIO,
        MODULO,
        "CODIGO UBICACIÓN",
        MUNICIPIO,
        EDIFICIO,
        PROPIETARIOS,
        "FOLIO / FINCA / FICHA",
        "FECHA DE INSCRIPCIÓN",
        PROPIETARIO,
        DOMICILIO,
        "USO DEL SUELO",
        "OTRO TIPO",
        DESCRIPCIÓN,
        "POR EDIFICIO",
        "% DE PROINDIVISO",
        "CÉDULA CATASTRAL",
        VALOR,
        "VALOR DEL TERRENO",
        "VALOR DE MEJORAS",
        "VALOR DEL TRASPASO",
        "NÚMERO DE PLANO",
        "FECHA DE CONSTRUCCIÓN",
        "FECHA DE OCUPACIÓN",
        LOTE,
        "SUPERFICIE INICIAL",
        "SUPERFICIE / RESTO LIBRE",
        COLINDANCIAS,
        "TIMESTAMP ADDED TO CSV",
        "DERECHOS / ACTOS / OTRAS OPERACIONES"
    )
    VALUES (
        OLD.FOLIO,
        OLD.MODULO,
        OLD."CODIGO UBICACIÓN",
        OLD.MUNICIPIO,
        OLD.EDIFICIO,
        OLD.PROPIETARIOS,
        OLD."FOLIO / FINCA / FICHA",
        OLD."FECHA DE INSCRIPCIÓN",
        OLD.PROPIETARIO,
        OLD.DOMICILIO,
        OLD."USO DEL SUELO",
        OLD."OTRO TIPO",
        OLD.DESCRIPCIÓN,
        OLD."POR EDIFICIO",
        OLD."% DE PROINDIVISO",
        OLD."CÉDULA CATASTRAL",
        OLD.VALOR,
        OLD."VALOR DEL TERRENO",
        OLD."VALOR DE MEJORAS",
        OLD."VALOR DEL TRASPASO",
        OLD."NÚMERO DE PLANO",
        OLD."FECHA DE CONSTRUCCIÓN",
        OLD."FECHA DE OCUPACIÓN",
        OLD.LOTE,
        OLD."SUPERFICIE INICIAL",
        OLD."SUPERFICIE / RESTO LIBRE",
        OLD.COLINDANCIAS,
        OLD."TIMESTAMP ADDED TO CSV",
        OLD."DERECHOS / ACTOS / OTRAS OPERACIONES"
    );
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.log_folios_changes() OWNER TO panaproperty;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Folios; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public."Folios" (
    id bigint NOT NULL,
    folio bigint NOT NULL,
    modulo text,
    codigo_ubicacion integer,
    municipio text,
    edificio text NOT NULL,
    propietarios text,
    folio_finca_ficha text,
    fecha_de_inscripcion date,
    propietario text,
    domicilio text,
    uso_del_suelo text,
    otro_tipo text,
    descripcion text,
    por_edificio text,
    porcentaje_de_proindiviso text,
    cedula_catastral text,
    valor numeric(19,2),
    valor_del_terreno numeric(19,2),
    valor_de_mejoras numeric(19,2),
    valor_del_traspaso numeric(19,2),
    numero_de_plano text,
    fecha_de_construccion date,
    fecha_de_ocupacion date,
    lote text,
    superficie_inicial text,
    superficie_resto_libre text,
    colindancias text,
    timestamp_added_to_csv timestamp with time zone,
    derechos_actos_otras_operaciones text
);


ALTER TABLE public."Folios" OWNER TO panaproperty;

--
-- Name: FoliosHistory; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public."FoliosHistory" (
    history_id integer NOT NULL,
    modulo text,
    codigo_ubicacion integer,
    municipio text,
    edificio text NOT NULL,
    propietarios text,
    folio_finca_ficha text,
    fecha_de_inscripcion date,
    propietario text,
    domicilio text,
    uso_del_suelo text,
    otro_tipo text,
    descripcion text,
    por_edificio text,
    porcentaje_de_proindiviso text,
    cedula_catastral text,
    valor numeric(20,2),
    valor_del_terreno numeric(20,2),
    valor_de_mejoras numeric(20,2),
    valor_del_traspaso numeric(20,2),
    numero_de_plano text,
    fecha_de_construccion date,
    fecha_de_ocupacion date,
    lote text,
    superficie_inicial text,
    superficie_resto_libre text,
    colindancias text,
    timestamp_added_to_csv timestamp with time zone,
    derechos_actos_otras_operaciones text,
    change_timestamp timestamp with time zone NOT NULL,
    folio_id bigint NOT NULL
);


ALTER TABLE public."FoliosHistory" OWNER TO panaproperty;

--
-- Name: FoliosHistory_history_id_seq; Type: SEQUENCE; Schema: public; Owner: panaproperty
--

ALTER TABLE public."FoliosHistory" ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FoliosHistory_history_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Folios_id_seq; Type: SEQUENCE; Schema: public; Owner: panaproperty
--

ALTER TABLE public."Folios" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Folios_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Metrics; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public."Metrics" (
    id bigint NOT NULL,
    codigo_ubicacion integer,
    municipio text,
    edificio text NOT NULL,
    fecha_de_construccion date,
    fecha_de_ocupacion date,
    propietarios text,
    domicilio text,
    sales_transaction_date date,
    valor numeric(19,2),
    valor_del_terreno numeric(19,2),
    valor_de_mejoras numeric(19,2),
    valor_del_traspaso numeric(19,2),
    superficie_inicial text,
    price_per_square_meter numeric(19,2),
    hipoteca boolean,
    monto numeric(19,2),
    tasa_efectiva numeric(19,2),
    tasa_nominal numeric(19,2),
    interes_anual numeric(19,2),
    feci numeric(19,2),
    interes_anual_feci numeric(19,2),
    nombre text,
    "timestamp" timestamp with time zone,
    uso_del_suelo text,
    folio_id bigint NOT NULL
);


ALTER TABLE public."Metrics" OWNER TO panaproperty;

--
-- Name: Metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: panaproperty
--

ALTER TABLE public."Metrics" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Metrics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PDF_Raw_Data; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public."PDF_Raw_Data" (
    id bigint NOT NULL,
    edificio text NOT NULL,
    filename text,
    pdf_text text,
    valor_del_terreno numeric(19,2),
    valor_de_mejoras numeric(19,2),
    valor_del_traspaso numeric(19,2),
    superficie_inicial text,
    sales_transaction_date date,
    hipoteca boolean NOT NULL,
    monto numeric(19,2),
    tasa_efectiva numeric(19,2),
    tasa_nominal numeric(19,2),
    interes_anual numeric(19,2),
    feci numeric(19,2),
    interes_anual_feci numeric(19,2),
    nombre text,
    filing_date date,
    folio_id bigint NOT NULL
);


ALTER TABLE public."PDF_Raw_Data" OWNER TO panaproperty;

--
-- Name: PDF_Raw_Data_id_seq; Type: SEQUENCE; Schema: public; Owner: panaproperty
--

ALTER TABLE public."PDF_Raw_Data" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PDF_Raw_Data_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_customuser; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public.accounts_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    is_superuser boolean NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    last_login timestamp with time zone NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    address text,
    classification character varying(50) NOT NULL,
    country character varying(100),
    currency_preference character varying(50) NOT NULL,
    language_preference character varying(50) NOT NULL,
    subscription_level character varying(50) NOT NULL,
    username character varying(100)
);


ALTER TABLE public.accounts_customuser OWNER TO panaproperty;

--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: panaproperty
--

ALTER TABLE public.accounts_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO panaproperty;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: panaproperty
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO panaproperty;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: panaproperty
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO panaproperty;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: panaproperty
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO panaproperty;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: panaproperty
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO panaproperty;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: panaproperty
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO panaproperty;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: panaproperty
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO panaproperty;

--
-- Name: folios; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public.folios (
    folio bigint NOT NULL,
    modulo text,
    "CODIGO UBICACIÓN" integer,
    municipio text,
    edificio text NOT NULL,
    propietarios text,
    "FOLIO / FINCA / FICHA" text,
    "FECHA DE INSCRIPCIÓN" date,
    propietario text,
    domicilio text,
    "USO DEL SUELO" text,
    "OTRO TIPO" text,
    "descripciÓn" text,
    "POR EDIFICIO" text,
    "% DE PROINDIVISO" text,
    "CÉDULA CATASTRAL" text,
    valor numeric,
    "VALOR DEL TERRENO" numeric,
    "VALOR DE MEJORAS" numeric,
    "VALOR DEL TRASPASO" numeric,
    "NÚMERO DE PLANO" text,
    "FECHA DE CONSTRUCCIÓN" date,
    "FECHA DE OCUPACIÓN" date,
    lote text,
    "SUPERFICIE INICIAL" text,
    "SUPERFICIE / RESTO LIBRE" text,
    colindancias text,
    "TIMESTAMP ADDED TO CSV" timestamp without time zone,
    "DERECHOS / ACTOS / OTRAS OPERACIONES" text
);


ALTER TABLE public.folios OWNER TO panaproperty;

--
-- Name: folioshistory; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public.folioshistory (
    historyid integer NOT NULL,
    folio bigint NOT NULL,
    modulo text,
    "CODIGO UBICACIÓN" integer,
    municipio text,
    edificio text NOT NULL,
    propietarios text,
    "FOLIO / FINCA / FICHA" text,
    "FECHA DE INSCRIPCIÓN" date,
    propietario text,
    domicilio text,
    "USO DEL SUELO" text,
    "OTRO TIPO" text,
    "descripciÓn" text,
    "POR EDIFICIO" text,
    "% DE PROINDIVISO" text,
    "CÉDULA CATASTRAL" text,
    valor numeric,
    "VALOR DEL TERRENO" numeric,
    "VALOR DE MEJORAS" numeric,
    "VALOR DEL TRASPASO" numeric,
    "NÚMERO DE PLANO" text,
    "FECHA DE CONSTRUCCIÓN" date,
    "FECHA DE OCUPACIÓN" date,
    lote text,
    "SUPERFICIE INICIAL" text,
    "SUPERFICIE / RESTO LIBRE" text,
    colindancias text,
    "TIMESTAMP ADDED TO CSV" timestamp without time zone,
    "DERECHOS / ACTOS / OTRAS OPERACIONES" text,
    changetimestamp timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.folioshistory OWNER TO panaproperty;

--
-- Name: folioshistory_historyid_seq; Type: SEQUENCE; Schema: public; Owner: panaproperty
--

CREATE SEQUENCE public.folioshistory_historyid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.folioshistory_historyid_seq OWNER TO panaproperty;

--
-- Name: folioshistory_historyid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: panaproperty
--

ALTER SEQUENCE public.folioshistory_historyid_seq OWNED BY public.folioshistory.historyid;


--
-- Name: metrics; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public.metrics (
    folio bigint NOT NULL,
    "CODIGO UBICACIÓN" integer,
    municipio text,
    edificio text NOT NULL,
    "FECHA DE CONSTRUCCIÓN" date,
    "FECHA DE OCUPACIÓN" date,
    propietarios text,
    domicilio text,
    "Sales Transaction Date" date,
    valor numeric,
    "VALOR DEL TERRENO" numeric,
    "VALOR DE MEJORAS" numeric,
    "VALOR DEL TRASPASO" numeric,
    "SUPERFICIE INICIAL" text,
    "Price per square meter" numeric,
    hipoteca boolean,
    monto numeric,
    "TASA EFECTIVA" numeric,
    "TASA NOMINAL" numeric,
    "INTERÉS ANUAL" numeric,
    feci numeric,
    "INTERÉS ANUAL + FECI" numeric,
    nombre text,
    "timestamp" timestamp without time zone,
    "USO DEL SUELO" text
);


ALTER TABLE public.metrics OWNER TO panaproperty;

--
-- Name: pdf_raw_data; Type: TABLE; Schema: public; Owner: panaproperty
--

CREATE TABLE public.pdf_raw_data (
    folio bigint NOT NULL,
    edificio text NOT NULL,
    filename text,
    "PDF Text" text,
    "VALOR DEL TERRENO" numeric,
    "VALOR DE MEJORAS" numeric,
    "VALOR DEL TRASPASO" numeric,
    "SUPERFICIE INICIAL" text,
    "Sales Transaction Date" date,
    hipoteca boolean,
    monto numeric,
    "TASA EFECTIVA" numeric,
    "TASA NOMINAL" numeric,
    "INTERÉS ANUAL" numeric,
    feci numeric,
    "INTERÉS ANUAL + FECI" numeric,
    nombre text,
    "Filing Date" date
);


ALTER TABLE public.pdf_raw_data OWNER TO panaproperty;

--
-- Name: folioshistory historyid; Type: DEFAULT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.folioshistory ALTER COLUMN historyid SET DEFAULT nextval('public.folioshistory_historyid_seq'::regclass);


--
-- Name: FoliosHistory FoliosHistory_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public."FoliosHistory"
    ADD CONSTRAINT "FoliosHistory_pkey" PRIMARY KEY (history_id);


--
-- Name: Folios Folios_folio_edificio_33e4e1a9_uniq; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public."Folios"
    ADD CONSTRAINT "Folios_folio_edificio_33e4e1a9_uniq" UNIQUE (folio, edificio);


--
-- Name: Folios Folios_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public."Folios"
    ADD CONSTRAINT "Folios_pkey" PRIMARY KEY (id);


--
-- Name: Metrics Metrics_folio_id_edificio_d3b46d75_uniq; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public."Metrics"
    ADD CONSTRAINT "Metrics_folio_id_edificio_d3b46d75_uniq" UNIQUE (folio_id, edificio);


--
-- Name: Metrics Metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public."Metrics"
    ADD CONSTRAINT "Metrics_pkey" PRIMARY KEY (id);


--
-- Name: PDF_Raw_Data PDF_Raw_Data_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public."PDF_Raw_Data"
    ADD CONSTRAINT "PDF_Raw_Data_pkey" PRIMARY KEY (id);


--
-- Name: accounts_customuser accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.accounts_customuser
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- Name: accounts_customuser accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.accounts_customuser
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: folios folios_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.folios
    ADD CONSTRAINT folios_pkey PRIMARY KEY (folio, edificio);


--
-- Name: folioshistory folioshistory_pkey; Type: CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.folioshistory
    ADD CONSTRAINT folioshistory_pkey PRIMARY KEY (historyid);


--
-- Name: FoliosHistory_folio_id_0b813f7a; Type: INDEX; Schema: public; Owner: panaproperty
--

CREATE INDEX "FoliosHistory_folio_id_0b813f7a" ON public."FoliosHistory" USING btree (folio_id);


--
-- Name: Metrics_folio_id_d7f2da06; Type: INDEX; Schema: public; Owner: panaproperty
--

CREATE INDEX "Metrics_folio_id_d7f2da06" ON public."Metrics" USING btree (folio_id);


--
-- Name: PDF_Raw_Data_folio_id_440a10fe; Type: INDEX; Schema: public; Owner: panaproperty
--

CREATE INDEX "PDF_Raw_Data_folio_id_440a10fe" ON public."PDF_Raw_Data" USING btree (folio_id);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: panaproperty
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_customuser USING btree (email varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: panaproperty
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: panaproperty
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: panaproperty
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: panaproperty
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: panaproperty
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: panaproperty
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: panaproperty
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: panaproperty
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: folios folios_update_trigger; Type: TRIGGER; Schema: public; Owner: panaproperty
--

CREATE TRIGGER folios_update_trigger AFTER UPDATE ON public.folios FOR EACH ROW EXECUTE FUNCTION public.log_folios_changes();


--
-- Name: FoliosHistory FoliosHistory_folio_id_0b813f7a_fk_Folios_id; Type: FK CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public."FoliosHistory"
    ADD CONSTRAINT "FoliosHistory_folio_id_0b813f7a_fk_Folios_id" FOREIGN KEY (folio_id) REFERENCES public."Folios"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Metrics Metrics_folio_id_d7f2da06_fk_Folios_id; Type: FK CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public."Metrics"
    ADD CONSTRAINT "Metrics_folio_id_d7f2da06_fk_Folios_id" FOREIGN KEY (folio_id) REFERENCES public."Folios"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PDF_Raw_Data PDF_Raw_Data_folio_id_440a10fe_fk_Folios_id; Type: FK CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public."PDF_Raw_Data"
    ADD CONSTRAINT "PDF_Raw_Data_folio_id_440a10fe_fk_Folios_id" FOREIGN KEY (folio_id) REFERENCES public."Folios"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: folioshistory folioshistory_folio_edificio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.folioshistory
    ADD CONSTRAINT folioshistory_folio_edificio_fkey FOREIGN KEY (folio, edificio) REFERENCES public.folios(folio, edificio);


--
-- Name: metrics metrics_folio_edificio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT metrics_folio_edificio_fkey FOREIGN KEY (folio, edificio) REFERENCES public.folios(folio, edificio);


--
-- Name: pdf_raw_data pdf_raw_data_folio_edificio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: panaproperty
--

ALTER TABLE ONLY public.pdf_raw_data
    ADD CONSTRAINT pdf_raw_data_folio_edificio_fkey FOREIGN KEY (folio, edificio) REFERENCES public.folios(folio, edificio);


--
-- PostgreSQL database dump complete
--

