# Generated by Django 5.0.6 on 2024-06-04 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("panaEstate", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pdfrawdata",
            unique_together=set(),
        ),
    ]
