# Generated by Django 5.0.6 on 2024-07-22 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaEstate', '0002_alter_pdfrawdata_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folios',
            options={'verbose_name_plural': 'Folios'},
        ),
        migrations.AlterModelOptions(
            name='folioshistory',
            options={'verbose_name_plural': 'Folios History'},
        ),
        migrations.AlterModelOptions(
            name='metrics',
            options={'verbose_name_plural': 'Metrics'},
        ),
        migrations.AlterModelOptions(
            name='pdfrawdata',
            options={'verbose_name_plural': 'PDF Raw Data'},
        ),
        migrations.CreateModel(
            name='PDFRawDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.TextField()),
                ('filename', models.TextField(blank=True, null=True)),
                ('pdf_text', models.TextField(blank=True, null=True)),
                ('valor_del_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('valor_de_mejoras', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('valor_del_traspaso', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('superficie_inicial', models.TextField(blank=True, null=True)),
                ('sales_transaction_date', models.DateField(blank=True, null=True)),
                ('hipoteca', models.BooleanField(default=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('tasa_efectiva', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('tasa_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('interes_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('feci', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('interes_anual_feci', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('pdf_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panaEstate.pdfrawdata')),
            ],
            options={
                'verbose_name_plural': 'PDF Raw Data History',
                'db_table': 'PDF_Raw_Data_History',
            },
        ),
        migrations.CreateModel(
            name='MetricsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ubicacion', models.IntegerField(blank=True, null=True)),
                ('municipio', models.TextField(blank=True, null=True)),
                ('edificio', models.TextField()),
                ('fecha_de_construccion', models.DateField(blank=True, null=True)),
                ('fecha_de_ocupacion', models.DateField(blank=True, null=True)),
                ('propietarios', models.TextField(blank=True, null=True)),
                ('domicilio', models.TextField(blank=True, null=True)),
                ('sales_transaction_date', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('valor_del_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('valor_de_mejoras', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('valor_del_traspaso', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('superficie_inicial', models.TextField(blank=True, null=True)),
                ('price_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('hipoteca', models.BooleanField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('tasa_efectiva', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('tasa_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('interes_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('feci', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('interes_anual_feci', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('uso_del_suelo', models.TextField(blank=True, null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panaEstate.metrics')),
            ],
            options={
                'verbose_name_plural': 'Metrics History',
                'db_table': 'Metrics_History',
                'unique_together': {('metric', 'edificio')},
            },
        ),
    ]
