# Generated by Django 5.0.6 on 2024-07-24 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaEstate', '0003_alter_folios_options_alter_folioshistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('address_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('district_id', models.IntegerField(blank=True, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telephone_nr', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_nr', models.CharField(blank=True, max_length=50, null=True)),
                ('fax_nr', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube_id', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('floors_count', models.IntegerField(blank=True, null=True)),
                ('construction_year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gmaps_place_id', models.CharField(max_length=255)),
                ('building_type', models.CharField(blank=True, max_length=50, null=True)),
                ('developer', models.CharField(blank=True, max_length=255, null=True)),
                ('amenities', models.CharField(blank=True, max_length=255, null=True)),
                ('occupancy_permit_date', models.DateField(blank=True, null=True)),
                ('registry_code', models.CharField(blank=True, max_length=50, null=True)),
                ('energy_certification', models.CharField(blank=True, max_length=50, null=True)),
                ('security_features', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_association', models.CharField(blank=True, max_length=255, null=True)),
                ('rentals_allowed', models.BooleanField(default=False)),
                ('rental_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='metrics',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panaEstate.building'),
        ),
    ]
