# Generated by Django 5.0.6 on 2024-07-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaEstate', '0004_building_metrics_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='folios',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panaEstate.building'),
        ),
        migrations.AddField(
            model_name='pdfrawdata',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panaEstate.building'),
        ),
    ]
