# Generated by Django 5.0.6 on 2024-08-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panaEstate', '0005_folios_building_pdfrawdata_building'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metricshistory',
            unique_together=set(),
        ),
    ]
