# Generated by Django 5.0.6 on 2024-09-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaEstate', '0007_barriosedificios_building_nombre_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='guid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
