# Generated by Django 5.0.6 on 2024-09-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaEstate', '0008_alter_building_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='guid',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
