# Generated by Django 5.0.6 on 2024-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaEstate', '0009_alter_building_guid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barriosedificios',
            options={'verbose_name_plural': 'Barrios'},
        ),
        migrations.AlterField(
            model_name='barriosedificios',
            name='guid',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='barriosedificios',
            name='nombre_barrio',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='barriosedificios',
            table='BarriosEdificios',
        ),
    ]
