# Generated by Django 5.0.6 on 2024-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name')),
                ('user_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=150, null=True, verbose_name='Subject')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ticket_number', models.CharField(max_length=8, unique=True, verbose_name='Ticket Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
