# Generated by Django 5.0.6 on 2024-08-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_es', models.CharField(max_length=255, verbose_name='Spanish Term')),
                ('description_es', models.TextField(verbose_name='Spanish Description')),
                ('term_en', models.CharField(max_length=255, verbose_name='English Term')),
                ('description_en', models.TextField(verbose_name='English Description')),
            ],
        ),
    ]
