# Generated by Django 5.0.6 on 2024-08-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_glossaryterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prompt_template', models.TextField(help_text='Use placeholders like {{building_name}}')),
                ('description', models.TextField(blank=True, help_text="A description of the template's purpose")),
            ],
        ),
    ]
