# Generated by Django 5.0.6 on 2024-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_aiprompttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsupport',
            name='description',
        ),
        migrations.AddField(
            model_name='contactsupport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Attach Files'),
        ),
        migrations.AddField(
            model_name='contactsupport',
            name='category',
            field=models.CharField(choices=[('Technical Support', 'Technical Support'), ('Feature Request', 'Feature Request'), ('New Building Request', 'New Building Request'), ('Other', 'Other')], default='Technical Support', max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='contactsupport',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Details of the Request'),
        ),
    ]
