# Generated by Django 5.0.6 on 2024-09-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_contactsupport_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsupport',
            name='attachment',
            field=models.FileField(blank=True, max_length=10000, null=True, upload_to='attachments/', verbose_name='Attach Files'),
        ),
    ]
