# Generated by Django 5.0.6 on 2024-05-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='classification',
            field=models.CharField(choices=[('Real Estate Agent', 'Real Estate Agent'), ('Broker', 'Broker'), ('Law Enforcement', 'Law Enforcement'), ('Investor', 'Investor'), ('Other', 'Other')], default='Real Estate Agent', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='currency_preference',
            field=models.CharField(default='USD', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language_preference',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_level',
            field=models.CharField(default='Free', max_length=50),
        ),
    ]
