# Generated by Django 5.0.6 on 2024-05-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_address_customuser_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.CharField(choices=[('Real Estate Agent', 'Real Estate Agent'), ('Broker', 'Broker'), ('Law Enforcement', 'Law Enforcement'), ('Investor', 'Investor'), ('Other', 'Other'), ('Administrator', 'Administrator')], default='Real Estate Agent', max_length=50),
        ),
    ]
