# Generated by Django 5.0.6 on 2024-05-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_level',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=50),
        ),
    ]
