# Generated by Django 5.0.6 on 2024-08-06 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_username'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('panaEstate', '0005_folios_building_pdfrawdata_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('can_download_summary_excel', models.BooleanField(default=False)),
                ('can_download_detailed_excel', models.BooleanField(default=False)),
                ('can_download_pdf', models.BooleanField(default=False)),
                ('can_view_detail', models.BooleanField(default=False)),
                ('can_view_history', models.BooleanField(default=False)),
                ('access_all_buildings', models.BooleanField(default=False)),
                ('accessible_buildings', models.ManyToManyField(blank=True, to='panaEstate.building')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
