# Generated by Django 5.0.6 on 2024-08-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_approval_status_and_more'),
        ('panaEstate', '0005_folios_building_pdfrawdata_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='accessible_buildings',
            field=models.ManyToManyField(blank=True, to='panaEstate.metrics'),
        ),
    ]
