# Generated by Django 5.0.6 on 2024-08-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_groupprofile_accessible_buildings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='access_all_buildings',
        ),
    ]
