# Generated by Django 5.0.6 on 2024-08-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_groupprofile_access_all_buildings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_level',
        ),
    ]
