# Generated by Django 5.0.6 on 2024-08-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_subscriptionlevel_customuser_subscription_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='classification',
        ),
    ]
