# Generated by Django 5.0.6 on 2024-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userclassification_customuser_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='enable_ai_analysis',
            field=models.BooleanField(default=False),
        ),
    ]
