# Generated by Django 5.0.6 on 2024-09-09 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panaEstate', '0007_barriosedificios_building_nombre_barrio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gravamen',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.IntegerField()),
                ('edificio', models.CharField(max_length=255)),
                ('organo_levantamiento', models.CharField(max_length=255)),
                ('nombre_organo', models.CharField(max_length=255)),
                ('provincia_organo', models.CharField(max_length=255)),
                ('num_oficio', models.CharField(max_length=50)),
                ('fecha_oficio', models.DateField()),
                ('num_auto', models.CharField(max_length=50)),
                ('fecha_auto', models.DateField()),
                ('descripcion', models.TextField()),
                ('titular_baja_nombre', models.CharField(max_length=255)),
                ('titular_baja_derecho', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('hora_registro', models.TimeField()),
                ('num_entrada', models.CharField(max_length=50)),
                ('doc_presentado_tipo', models.CharField(max_length=255)),
                ('doc_presentado_fecha', models.DateField()),
                ('nombre_juez', models.CharField(max_length=255)),
                ('derechos_registro', models.CharField(max_length=255)),
                ('nombre_archivo_pdf', models.CharField(max_length=255)),
                ('contenido_pdf', models.TextField()),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panaEstate.building')),
            ],
        ),
        migrations.CreateModel(
            name='Remate',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.IntegerField()),
                ('edificio', models.CharField(max_length=255)),
                ('organo_remate', models.CharField(max_length=255)),
                ('nombre_organo', models.CharField(max_length=255)),
                ('provincia_organo', models.CharField(max_length=255)),
                ('num_acta_remate', models.CharField(max_length=50)),
                ('fecha_acta_remate', models.DateField()),
                ('num_auto', models.CharField(max_length=50)),
                ('fecha_auto', models.DateField()),
                ('num_oficio', models.CharField(max_length=50)),
                ('fecha_oficio', models.DateField()),
                ('observaciones', models.TextField()),
                ('titular_baja_nombre', models.CharField(max_length=255)),
                ('titular_baja_cedula', models.CharField(max_length=50)),
                ('titular_baja_derecho', models.CharField(max_length=50)),
                ('nuevo_titular_nombre', models.CharField(max_length=255)),
                ('nuevo_titular_derecho', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('hora_registro', models.TimeField()),
                ('doc_presentado_tipo', models.CharField(max_length=255)),
                ('doc_presentado_num', models.CharField(max_length=50)),
                ('doc_presentado_fecha', models.DateField()),
                ('num_entrada', models.CharField(max_length=50)),
                ('nombre_juez', models.CharField(max_length=255)),
                ('derechos_registro', models.CharField(max_length=255)),
                ('nombre_archivo_pdf', models.CharField(max_length=255)),
                ('contenido_pdf', models.TextField()),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panaEstate.building')),
            ],
        ),
    ]
