# Generated by Django 5.0.6 on 2024-09-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravamen',
            name='num_auto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gravamen',
            name='num_entrada',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gravamen',
            name='num_oficio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gravamen',
            name='titular_baja_derecho',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='remate',
            name='doc_presentado_num',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='remate',
            name='nuevo_titular_derecho',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='remate',
            name='num_acta_remate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='remate',
            name='num_auto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='remate',
            name='num_entrada',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='remate',
            name='num_oficio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='remate',
            name='titular_baja_cedula',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='remate',
            name='titular_baja_derecho',
            field=models.CharField(max_length=500),
        ),
    ]
