# Generated by Django 5.0.6 on 2024-09-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_info', '0002_alter_gravamen_num_auto_alter_gravamen_num_entrada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gravamen',
            options={'verbose_name': 'Gravamenes', 'verbose_name_plural': 'Gravamenes'},
        ),
    ]
